### ISSUE TITLE
When breaking the Hatchery cause server crash

### ISSUE THREAD

**Issue by catmunyi** [joshiejack/Piscary#2]
Breaking the Hatchery and it did not break. Has a chance to cause server crash.
Crash Report : 
[crash-2021-07-01_14.42.40-server.txt](https://github.com/Harvest-Festival/Piscary/files/6749115/crash-2021-07-01_14.42.40-server.txt)

**Comment by joshiejack** [comment]
Will take a look at it this evening. But I was able to confirm it just before I left for work.
