### ISSUE TITLE
Hatchery is a ticking entity on dedicated server

### ISSUE THREAD

**Issue by karltroid51** [joshiejack/Piscary#3]
Hi! I'm using this mod on a heavily modded dedicated server with me and my friends, and there's some heavy desync, which, in later testing revealed that the hatchery was a ticking entity. Placing it down makes it briefly disappear, and it reappears when I right-click the block where it's supposed to be; it also doesn't leave your inventory unless you throw it away, and I can't use it for it's intended purpose.

Attached is the crash log. Thank you for any help in advance!
[crash-2021-07-05_04.42.51-server.txt](https://github.com/Harvest-Festival/Piscary/files/6761750/crash-2021-07-05_04.42.51-server.txt)

**Comment by joshiejack** [comment]
Update the mod to 1.0.2.
